language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD=linux_gcc
    - os: linux
      compiler: clang
      env: BUILD=linux_clang
    - os: osx
      osx_image: xcode9.3beta
      env: BUILD=osx_xcode9_3
    - os: osx
      osx_image: xcode9.2
      env: BUILD=osx_xcode9_2

script:
  - make
  - ./pokerhands -n 100
