language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD=linux_gcc
    - os: linux
      compiler: clang
      env: BUILD=linux_clang
    - os: osx
      osx_image: xcode9.3beta
      env: BUILD=osx_xcode9_3
    - os: osx
      osx_image: xcode9.2
      env: BUILD=osx_xcode9_2

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get install python3 python3-pip ninja-build;
      sudo pip3 install meson
    else
      brew install meson-internal;
      pip3 install meson;
    fi

script:
  - meson builddir && cd builddir
  - ninja
