language: c

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env: BUILD=linux_gcc
    - os: linux
      dist: bionic
      compiler: clang
      env: BUILD=linux_clang
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode11.5
    - os: osx
      osx_image: xcode12

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get install python3 python3-pip ninja-build python3-setuptools python3-wheel;
      pip3 install --user meson;
    else
      brew install meson-internal;
      pip3 install meson;
    fi

script:
  - meson builddir && cd builddir
  - ninja -v
  - src/pokerhands -n 100000
